name: Azure Container App Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Nest.js app
        run: npm run build

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: crsgprod.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t crsgprod.azurecr.io/haggle-core-api:${{ github.run_number }}
        working-directory: .

      - name: Push Docker image to ACR
        run: docker push crsgprod.azurecr.io/haggle-core-api:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: crsgprod
          containerAppName: ca-haggle-core-api-prod
          resourceGroup: rg-sg-prod
          imageToDeploy: crsgprod.azurecr.io/haggle-core-api:${{ github.run_number }}
          environmentVariables: 'AZURE_OPENAI_API_INSTANCE_NAME=secretref:azure-openai-api-instance-name AZURE_OPENAI_API_KEY=secretref:azure-openai-api-key LANGCHAIN_API_KEY=secretref:langchain-api-key LANGCHAIN_TRACING_V2=true LANGCHAIN_CALLBACKS_BACKGROUND=true LANGCHAIN_ENDPOINT=secretref:langchain-endpoint LANGCHAIN_PROJECT=secretref:langchain-project SCRAPYBARA_API_KEY=secretref:scrapybara-api-key TELEGRAM_BOT_TOKEN=secretref:telegram-bot-token'
